name: Deploy Infrastructure

on: workflow_dispatch

env:
  INFRASTRUCTURE_DIRECTORY: "./src"

jobs:
  deploy:
    name: Validate & Deploy Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Set environment
        run: |
          case ${GITHUB_REF##*/} in
            "production") echo "ENVIRONMENT=production" >> $GITHUB_ENV ;;
            "preprod") echo "ENVIRONMENT=preprod" >> $GITHUB_ENV ;;
            "qa") echo "ENVIRONMENT=qa" >> $GITHUB_ENV ;;
            *) echo "ENVIRONMENT=development" >> $GITHUB_ENV ;;
          esac

      - name: Checkout Repo
        uses: actions/checkout@v2
      
      - name: Install Node 16
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:  ${{ secrets.AWS_REGION }}

      - name: Install Terraform CDK & dependencies
        working-directory: ${{ env.INFRASTRUCTURE_DIRECTORY }}
        run: npm install

      - name: Run Terraform CDK Unit Tests
        working-directory: ${{ env.INFRASTRUCTURE_DIRECTORY }}
        run: npm run test

      - name: Deploy with Terraform CDK
        working-directory: ${{ env.INFRASTRUCTURE_DIRECTORY }}
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_TERRAFORM_BUCKET: ${{ secrets.AWS_TERRAFORM_BUCKET }}
          SERVICE_NAME: ${{ secrets.SERVICE_NAME }}
        run: cdktf deploy --auto-approve