name: Run Unit Tests

on:
  push:
      branches:
        - "**"

env:
  INFRASTRUCTURE_DIRECTORY: "./src"

jobs:
  deploy:
    name: Run Terraform CDK Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install Terraform CDK
        run: npm install --global cdktf-cli@0.12.2

      - name: Install dependencies
        working-directory: ${{ env.INFRASTRUCTURE_DIRECTORY }}
        run: npm install

      - name: Run Terraform CDK Unit Tests
        working-directory: ${{ env.INFRASTRUCTURE_DIRECTORY }}
        run: npm run test